server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: BiblioPlus
  datasource:
    url: ${DB_URL}
    username: ${DB_POSTGRES_USER}
    password: ${DB_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui-path: /biblioplus.html
  api-docs:
    path: /biblioplus
  packagesToScan: com.emanuel.BiblioPlus.modules

api:
  security:
    token:
      secret: ${API_SECRET:0f0d41788a7922e183c1695473fe256d}
      access-token:
        expiration-hour: 1
      refresh-token:
        expiration-hour: 12

biblioplus:
  url: ${API_URL:http://localhost:8082}
